declare namespace NodeJS {
  export interface ProcessEnv {
    EXPO_PUBLIC_TW_CLIENT_ID: string;
    EXPO_PUBLIC_EAS_CONTRACT: string;
    EXPO_PUBLIC_SCHEMA_ADDRESS_ACTION: string;
    EXPO_PUBLIC_SCHEMA_ADDRESS_REVIEW: string;
    EXPO_PUBLIC_EAS_SCHEMA_REGISTRY: string;
    EXPO_PUBLIC_EAS_BASE_URL: string;
    EXPO_PUBLIC_API_KEY_GOOGLE: string;
    EXPO_PUBLIC_ORGANIZATION_MANAGER_ADDRESS: string;
    EXPO_PUBLIC_SUPABASE_URL: string;
    THIRDWEB_AUTH_PRIVATE_KEY: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY: string;
    EXPO_PUBLIC_SERVER_URL: string;
  }
}
